---
 - name: Install CUP Packages 
   hosts: localhost
   become: true 
   vars: 
     install_package:
        - cups-filters
        - cups-filters-libs
          
   tasks: 
      - name: Install package
        ansible.builtin.yum:
          name: "{{ item }}"
          state: latest 
        loop: "{{ install_package }}"
